version: '3'

services:
  # Attacker machine
  attacker:
    image: kalilinux/kali-rolling
    container_name: attacker
    hostname: attacker
    command: bash -c "apt-get update && apt-get install -y nmap hping3 netcat-traditional python3 sqlmap && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      demo_network:
        ipv4_address: 172.18.0.10

  # Cloud infrastructure simulation
  cloud-server:
    image: ubuntu:22.04
    container_name: cloud-server
    hostname: cloud-server
    command: bash -c "apt-get update && apt-get install -y nginx net-tools && service nginx start && tail -f /dev/null"
    networks:
      demo_network:
        ipv4_address: 172.18.0.20

  # Database server
  db-server:
    image: mysql:8.0
    container_name: db-server
    hostname: db-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer_db
    ports:
      - "3306:3306"
    networks:
      demo_network:
        ipv4_address: 172.18.0.30

  # API gateway (using Nginx)
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    hostname: api-gateway
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      demo_network:
        ipv4_address: 172.18.0.40

  # IDS monitoring system
  ids-server:
    image: ubuntu:22.04
    container_name: ids-server
    hostname: ids-server
    command: bash -c "apt-get update && apt-get install -y suricata net-tools tcpdump && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./suricata-config:/etc/suricata
      - ./suricata-logs:/var/log/suricata
    networks:
      demo_network:
        ipv4_address: 172.18.0.50

  # ELK Stack (Elasticsearch, Logstash, Kibana)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      demo_network:
        ipv4_address: 172.18.0.51

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./suricata-logs:/suricata-logs
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      demo_network:
        ipv4_address: 172.18.0.52

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      demo_network:
        ipv4_address: 172.18.0.53

  # EVEBox for alert management
  evebox:
    image: jasonish/evebox:latest
    container_name: evebox
    ports:
      - "5636:5636"
    depends_on:
      - elasticsearch
    command: >
      evebox server 
      --host 0.0.0.0 
      --port 5636 
      --elasticsearch "http://elasticsearch:9200" 
      --index "suricata-*" 
      --no-check-certificate
    networks:
      demo_network:
        ipv4_address: 172.18.0.60

networks:
  demo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24